image: rust

build:
  script:
    - cargo build

test:
  script:
    - cargo test

clippy:
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

rustfmt:
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
